import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; // ✅ Import your context Provider
// import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ai Interview Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
       <Provider>
          {children}

        </Provider>
        {/* <Toaster /> */}
      </body>
    </html>
  );
}
