import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider"; // ✅ Import your context Provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ai Interview Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <Provider> {/* ✅ wrap entire app with context */}
          {children}
        </Provider>
      </body>
    </html>
  );
}
